### ISSUE TITLE
Allow dynamic props on Icons

### ISSUE THREAD

**Issue by futursolo** [pedrodesu/yew-feather#11]
Currently all props on icons are marked as `&'static str`, which means that it must be specified as a string literal.

Would it be possible to change the type of properties to `AttrValue` so that dynamic variables can be used?

https://docs.rs/yew/0.19.3/yew/virtual_dom/enum.AttrValue.html

**Comment by pedrodesu** [comment]
Will take care of that ASAP, was not aware of such a possibility; Thanks for the heads up.

**Comment by pedrodesu** [comment]
Solved in the last version. Thoroughly tested, but if there seems to exist a problem do let me know.
