### ISSUE TITLE
The trait `yew::Component` is not implemented for `yew::functional::FunctionComponent<yew_feather::camera::camera>

### ISSUE THREAD

**Issue by ItFlyingStart** [pedrodesu/yew-feather#12]
I try to make use of yew-feather, but I get the build error below. Can you help?

use yew::prelude::*;
use yew::{function_component, html};
use yew_feather::camera::Camera;

#[function_component(Sidebar)]
pub fn sidebar() -> Html {
    html! { <Camera /> }
}

<img width="754" alt="vmplayer_B28ML42qQf" src="https://user-images.githubusercontent.com/5562995/160235083-e37ec979-5d96-4239-9b6f-a5c4c03c707a.png">

**Comment by invokermain** [comment]
Same here, I think this library doesn't work for yew 0.20? @pedrodesu sorry for ping but see this issue is almost a year old with no reply.

**Comment by pedrodesu** [comment]
It was probably a problem with versioning. The last commit bumps versions and does some fixes, thus solving this problem. Do let me know if it doesn't seem to work.
