### ISSUE TITLE
Interested in a PR from my fork?

### ISSUE THREAD

**Issue by WorldSEnder** [pedrodesu/yew-feather#6]
I've [forked yew-feather](https://github.com/WorldSEnder/yew-feather) a few months ago under the assumption that you were not inactive. Thanks for coming back. Wondering, would you appreciate a PR? Let me summarize the changes I did:

1. Write a working `build.rs` script. This allows to cargo to compile the crate out of the box without preprocessing such as running `npm run-script build`. Makes easier to replace the dependency with a git dependency when overriding should yew continue to add breaking changes.
2. With the above, build fully in rust, including filling in the `slug.rs` file. This apparently speeds up compile time on my end compares to the js version.
3. Add a `package.lock` file to fix the version of `feather-icons` to depend on. No surprises and subtle differences in icon definitions.
4. Reuse the same Properties struct for all icons. This is mainly a codegen issue where expanding and checking all the derived `impl Property` etc has heavy costs which are sidestepping by reusing the properties struct. This alone cut compile times down from 10s to under 4s on my end. The rest seems to be the few hundred of icons definitions. It might be worth to add some (granular) features to enable/disable some icons to make this even faster. Keep in mind the timing is a crude wall-time measurement of this crate only I got from `-Z timings` and includes the download of `feather-icons`.
5. Upgrade the slug code to yew 0.19. I see you bumped the dependency version but didn't yet modify the code.

Let me know what you think, looking forward :tada:

**Comment by pedrodesu** [comment]
I appreciate the time you took to build that fork. I have indeed been a little inactive in regards to programming lately.

Your fork seems very interesting. Just one safety question, was it tested? I'll check nonetheless. After that, I shall submit a PR.

Having in account the changes you've made, feel free to add yourself to the authors list of your fork, which, as aforementioned, I shall pull when I'm able to. Let me just know beforehand if you'd like that; Then I shall proceed.
