### ISSUE TITLE
Event listener for icons 

### ISSUE THREAD

**Issue by vedpatil611** [pedrodesu/yew-feather#8]
A way to add onclick to icon would be really nice.
`<XCircle size=20 onclick={remove_item}>`

**Comment by pedrodesu** [comment]
Although doable, I believe it's debatable on whether such a change should be done.

I'd like to remember the components ultimately return SVG elements. Should an SVG element be able to listen to such an event? Don't you think it would make more sense to attach the event to a parent element such as a button or something of that sort?

Although `yew-feather` is a standalone package, we try to follow the rationale of other Feather component wrappers, such as `react-feather`, and while they do accept generic, variadic props (something we can't quite do in Rust, given it's a strongly, static typed language), they don't explicitly accept listeners in their components.

Furthermore, I'd like to note virtually any child of an SVG element could have such listeners attached, so allowing listeners to the component itself seems a bit ambiguous.
Any thoughts?
